package dsu.se231027.policemanagementsystem.GUI;

/**
 *
 * @author Hamza Nizamani
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Background = new javax.swing.JPanel();
        Head = new javax.swing.JPanel();
        TitleText = new javax.swing.JLabel();
        Body = new javax.swing.JPanel();
        TagTitleLabel = new javax.swing.JLabel();
        SelectionPanel = new javax.swing.JPanel();
        ButtonLodgeFir = new javax.swing.JButton();
        ButtonRegisterComplaint = new javax.swing.JButton();
        ButtonCriminalReport = new javax.swing.JButton();
        ButtonManageStaff = new javax.swing.JButton();
        ButtonViewCases = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Head.setBackground(java.awt.SystemColor.controlHighlight);

        TitleText.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        TitleText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleText.setText("Police Management System");

        javax.swing.GroupLayout HeadLayout = new javax.swing.GroupLayout(Head);
        Head.setLayout(HeadLayout);
        HeadLayout.setHorizontalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HeadLayout.setVerticalGroup(
            HeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeadLayout.createSequentialGroup()
                .addComponent(TitleText, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );

        Body.setBackground(java.awt.SystemColor.controlHighlight);
        Body.setLayout(new java.awt.BorderLayout());

        TagTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TagTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TagTitleLabel.setText("Police Management System Admin Dashboard");
        TagTitleLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        TagTitleLabel.setFocusable(false);
        Body.add(TagTitleLabel, java.awt.BorderLayout.CENTER);

        SelectionPanel.setPreferredSize(new java.awt.Dimension(530, 270));
        SelectionPanel.setLayout(new java.awt.GridBagLayout());

        ButtonLodgeFir.setBackground(new java.awt.Color(99, 124, 233));
        ButtonLodgeFir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonLodgeFir.setForeground(new java.awt.Color(255, 255, 255));
        ButtonLodgeFir.setText("File an FIR");
        ButtonLodgeFir.setMaximumSize(new java.awt.Dimension(200, 200));
        ButtonLodgeFir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLodgeFirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 82;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 53, 0, 0);
        SelectionPanel.add(ButtonLodgeFir, gridBagConstraints);

        ButtonRegisterComplaint.setBackground(new java.awt.Color(114, 160, 92));
        ButtonRegisterComplaint.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonRegisterComplaint.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegisterComplaint.setText("Register Complaint");
        ButtonRegisterComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegisterComplaintActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 31;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 251, 0, 54);
        SelectionPanel.add(ButtonRegisterComplaint, gridBagConstraints);

        ButtonCriminalReport.setBackground(new java.awt.Color(223, 193, 94));
        ButtonCriminalReport.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonCriminalReport.setForeground(new java.awt.Color(255, 255, 255));
        ButtonCriminalReport.setText("Criminal Report");
        ButtonCriminalReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCriminalReportActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 53, 0, 0);
        SelectionPanel.add(ButtonCriminalReport, gridBagConstraints);

        ButtonManageStaff.setBackground(new java.awt.Color(114, 157, 175));
        ButtonManageStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonManageStaff.setForeground(new java.awt.Color(255, 255, 255));
        ButtonManageStaff.setText("Manage Staff");
        ButtonManageStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonManageStaffActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 251, 0, 54);
        SelectionPanel.add(ButtonManageStaff, gridBagConstraints);

        ButtonViewCases.setBackground(new java.awt.Color(169, 78, 78));
        ButtonViewCases.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ButtonViewCases.setForeground(new java.awt.Color(255, 255, 255));
        ButtonViewCases.setText("View Cases");
        ButtonViewCases.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonViewCasesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 504;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 53, 26, 54);
        SelectionPanel.add(ButtonViewCases, gridBagConstraints);

        Body.add(SelectionPanel, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Head, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Head, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Body, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(Background, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCriminalReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCriminalReportActionPerformed
        
    }//GEN-LAST:event_ButtonCriminalReportActionPerformed

    private void ButtonLodgeFirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLodgeFirActionPerformed

        new RegisterFIR().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_ButtonLodgeFirActionPerformed

    private void ButtonRegisterComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegisterComplaintActionPerformed
        dispose();
        new RegisterComplaint().setVisible(true);
        
    }//GEN-LAST:event_ButtonRegisterComplaintActionPerformed

    private void ButtonViewCasesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonViewCasesActionPerformed
        dispose();
        new ViewCases().setVisible(true);
    }//GEN-LAST:event_ButtonViewCasesActionPerformed

    private void ButtonManageStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonManageStaffActionPerformed
        dispose();
        new ManageStaff().setVisible(true);
    }//GEN-LAST:event_ButtonManageStaffActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel Body;
    private javax.swing.JButton ButtonCriminalReport;
    private javax.swing.JButton ButtonLodgeFir;
    private javax.swing.JButton ButtonManageStaff;
    private javax.swing.JButton ButtonRegisterComplaint;
    private javax.swing.JButton ButtonViewCases;
    private javax.swing.JPanel Head;
    private javax.swing.JPanel SelectionPanel;
    private javax.swing.JLabel TagTitleLabel;
    private javax.swing.JLabel TitleText;
    // End of variables declaration//GEN-END:variables
}
